export const color = {
  black: 'data:image/gif;base64,R0lGODlhAQABAPAAAD09PQAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==',
  white: 'data:image/gif;base64,R0lGODlhAQABAPAAAP///wAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==',
  gray: 'data:image/gif;base64,R0lGODlhAQABAPAAAO7u7gAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=='
}
